version: "3.7"
services:
  backend:
    container_name: backend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - "APP_DB_USERNAME:${APP_DB_USERNAME}"
      - "APP_DB_PASSWORD:${APP_DB_PASSWORD}"
      - "APP_DB_NAME:${APP_DB_NAME}"
      - "APP_DB_PORT:${APP_DB_PORT}"
      - "APP_DB_HOST:${APP_DB_HOST}"
      - "APP_PORT:${APP_PORT}"
  db:
    container_name: db
    image: postgres
    environment:
      - "POSTGRES_USER:${POSTGRES_USER}"
      - "POSTGRES_PASSWORD:${POSTGRES_PASSWORD}"
      - "POSTGRES_DB:${POSTGRES_DB}"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped


volumes:
  postgres: