version: "3.7"
services:
  backend:
    container_name: backend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=jumia
    volumes:
      - postgres:/data/postgres
      - ./init.sh:/docker-entrypoint/init.sh
    ports:
      - "5432:5432"


volumes:
  postgres: