version: "3.7"
services:
  backend:
    container_name: backend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db_test
  db_test:
    container_name: db_test
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=jumia_test
    ports:
      - "5432:5432"