// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// FnOptions is an autogenerated mock type for the FnOptions type
type FnOptions struct {
	mock.Mock
}

// Execute provides a mock function with given fields: tx
func (_m *FnOptions) Execute(tx *gorm.DB) (*gorm.DB, error) {
	ret := _m.Called(tx)

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB) error); ok {
		r1 = rf(tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
