// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// RoutingGroup is an autogenerated mock type for the RoutingGroup type
type RoutingGroup struct {
	mock.Mock
}

// Routes provides a mock function with given fields: _a0, _a1
func (_m *RoutingGroup) Routes(_a0 *gin.Engine, _a1 interface{}) {
	_m.Called(_a0, _a1)
}
