// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	entity "Jumia_todoList/entity"

	mock "github.com/stretchr/testify/mock"

	model "Jumia_todoList/api/model"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *UseCase) Create(_a0 model.TaskCreateInput) (int, error) {
	ret := _m.Called(_a0)

	var r0 int
	if rf, ok := ret.Get(0).(func(model.TaskCreateInput) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.TaskCreateInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0
func (_m *UseCase) Delete(_a0 model.TaskRemoveInput) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TaskRemoveInput) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Filter provides a mock function with given fields: input
func (_m *UseCase) Filter(input model.TaskFilterInput) ([]entity.Task, error) {
	ret := _m.Called(input)

	var r0 []entity.Task
	if rf, ok := ret.Get(0).(func(model.TaskFilterInput) []entity.Task); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.TaskFilterInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *UseCase) Get(id int) []entity.Task {
	ret := _m.Called(id)

	var r0 []entity.Task
	if rf, ok := ret.Get(0).(func(int) []entity.Task); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Task)
		}
	}

	return r0
}

// Update provides a mock function with given fields: _a0
func (_m *UseCase) Update(_a0 model.TaskUpdateInput) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TaskUpdateInput) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
