// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	zerolog "github.com/rs/zerolog"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Load provides a mock function with given fields: _a0, _a1
func (_m *Repository) Load(_a0 *zerolog.Logger, _a1 *gorm.DB) {
	_m.Called(_a0, _a1)
}
